name: Oak
options:
  minimumXcodeGenVersion: 2.39.0
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    PRODUCT_BUNDLE_IDENTIFIER: com.oak.focus
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
targets:
  Oak:
    type: application
    platform: macOS
    sources:
      - path: Oak/Oak
        excludes:
          - "**/*.entitlements"
    entitlements:
      path: Oak/Oak/Oak.entitlements
    settings:
      base:
        PRODUCT_NAME: Oak
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Oak
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        SWIFT_EMIT_LOC_STRINGS: YES
    scheme:
      testTargets: []
