name: Oak
options:
  xcodeVersion: "17.0"
attributes:
  LastSwiftUpdateCheck: 1700
targets:
  Oak:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Oak
        excludes:
          - "**/*.entitlements"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oak.app
      MARKETING_VERSION: 0.0.0
      CURRENT_PROJECT_VERSION: 1
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_CFBundleShortVersionString: $(MARKETING_VERSION)
      INFOPLIST_KEY_CFBundleVersion: $(CURRENT_PROJECT_VERSION)
      INFOPLIST_KEY_LSUIElement: true
      GENERATE_INFOPLIST_FILE: true
    scheme:
      testTargets:
        - OakTests

  OakTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Tests/OakTests
    dependencies:
      - target: Oak
    settings:
      GENERATE_INFOPLIST_FILE: true
