name: Oak
targets:
  Oak:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Oak
        excludes:
          - "**/*.entitlements"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oak.app
      INFOPLIST_KEY_LSUIElement: true
      INFOPLIST_KEY_LSBackgroundOnly: true
      GENERATE_INFOPLIST_FILE: true
    scheme:
      testTargets:
        - OakTests

  OakTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Tests/OakTests
    dependencies:
      - target: Oak
    settings:
      GENERATE_INFOPLIST_FILE: true
