name: Oak
options:
  xcodeVersion: "17.0"
attributes:
  LastSwiftUpdateCheck: 1700
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.4
targets:
  Oak:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Oak
        excludes:
          - "**/*.entitlements"
    dependencies:
      - package: Sparkle
        product: Sparkle
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.productsway.oak.app
      MARKETING_VERSION: 0.5.15
      CURRENT_PROJECT_VERSION: 5015
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: Oak/Info.plist
      SPARKLE_PUBLIC_ED_KEY: IjFqN1R6i4Dh8IZxQ42RtSEii7pUgS45+NvidSwQup0=
    scheme:
      testTargets:
        - OakTests

  OakTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Tests/OakTests
    dependencies:
      - target: Oak
    settings:
      GENERATE_INFOPLIST_FILE: true
